//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Authentiqr.NET")]
[assembly: AssemblyVersion("8.0.0")]
[assembly: AssemblyFileVersion("8.0.0")]
[assembly: AssemblyInformationalVersion("8.0.0")]
[assembly: AssemblyCopyright("Copyright (c) Richard Green 2011 - 2024")]

